# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 371a0c82756ec483d8c6f46d3af524203f8f3f35dfc4f0c0ada002ab9eab89f0e395105696f75e01fd2778101cd4f1b3cac83ebb3a4270c6bf1e084d8cd6e767

test:
  secret_key_base: 8e7fbf123661fd36f701630f9577c11bbc9a72222fc20a960885b2d7c55337628d3c32efd77760168b7b13b940f9853095347abc1dc31efcf62b31036726ef11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
